### ISSUE TITLE
js8msg for raspberryPi please

### ISSUE THREAD

**Issue by maxlinux2000** [tkocou/new_JS8msg#1]
Hi, as subject please add a version for arm32 in the build.

the current version there are only amd64 an windows 10

```
$ file js8msg2 
js8msg2: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f6af5bc244c001328c174a6abf855d682aa7401b, for GNU/Linux 2.6.32, stripped

```

or add a document how to compile the program

tnx
MaX

**Comment by tkocou** [comment]
Thank you for the suggestion. I will look into the possibility.

**Comment by maxlinux2000** [comment]
ok I found that executing the js8msg2.py file, the interface run.

**Comment by tkocou** [comment]
Makes sense. Make sure you have python3 installed on your PI. Just copy all the *.py files into the "~/pi/bin" directory, set the execute permissions on js8msg2.py and execute js8msg2.py. The JS8msg directory will be created with it's subdirectories, as well as the needed files in the subdirectories.
